tap 'homebrew/cask-fonts'
tap 'homebrew/cask'
tap 'mas-cli/tap'

cask_args appdir: '/Applications'

brew 'awscli'
brew 'dive'
brew 'git-sizer'
brew 'jq'
brew 'k3d'
brew 'kubectl'
brew 'mas-cli/tap/mas'
brew 'neofetch'
brew 'pipx'
brew 'rcm'
brew 'starship'
brew 'terraform'
brew 'terragrunt'
brew 'tmux'
brew 'yq'

cask '1password'
cask 'aws-vault'
cask 'bartender'
cask 'font-fira-code'
cask 'font-fira-mono-nerd-font'
cask 'google-chrome'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'vlc'

mas 'Telegram', id: 747648890
mas 'EasyRes', id: 688211836
mas 'Xcode', id: 497799835
mas 'Bear', id: 1091189122
mas 'Spark', id: 1176895641
