# zmodload zsh/zprof

export ZSH="$HOME/.oh-my-zsh"
export ZSH_DISABLE_COMPFIX=true
export TERM='xterm-256color'
export ZSH_THEME="robbyrussell"

plugins=(git docker docker-compose aws zsh-autosuggestions brew)

source $ZSH/oh-my-zsh.sh

typeset -U config_files
config_files=(~/.zsh/*.zsh)

for file in ${config_files}
do
  source $file
done

neofetch

# zprof